### ISSUE TITLE
Difficulty selection UI behaves weirdly / doesn't always work

### ISSUE THREAD

**Issue by kartoFlane** [kartoFlane/ITB-ModLoader#100]
Seems like the clicks are not correctly intercepted / sometimes not even passed to modded UI and instead going straight to the game. Most likely caused by recent UI rework - probably the element is marked as hovered one frame too late, causing it to not intercept mouse events.

Attempted incomplete fix here: https://github.com/Lemonymous/ITB-ModLoader/tree/test-ui-mouse-events

**Comment by Lemonymous** [comment]
Additional details of "weirdness":

From my testing, pressing the left arrow will cycle through difficulties correctly: Impossible > Very Hard > Hard > Normal > Easy
However, pressing the right arrow will cycle through difficulties incorrectly: Easy > Normal > Normal > Normal > Impossible

**Comment by Lemonymous** [comment]
Another update to this issue.
The issue started happening after this commit: 81a30ee4a9179a9466d477d1b72cf1e73daed78b


What happens is this:
In modui/extra_difficulty.lua, arrLeft and arrRight is created.
The way I set them up was so that the custom buttons would pass through mousedown events to the game if we were pressing real difficulty levels.
This way the vanilla game buttons would be clicked so that we would cycle through the real Easy/Normal/Hard difficulties. Only when going past this (V.Hard, Imposs) would we suppress mousedown events to the game so that the real buttons would not be clicked.

The problem that was introduced in the commit in question, was that the logic for what happened when a hovered/pressed button did not consume the mouse event changed. Now, instead of just passing the mouse event through to the game, the mod loader's mouse event handler will pass this event to each ui element under the cursor; and for a second time call mousedown for arrLeft/arrRight.

The buttons will therefor get out of sync with where we expect them to be.

**Comment by kartoFlane** [comment]
Fixed in #117
