### ISSUE TITLE
Improve accessibility of mod options

### ISSUE THREAD

**Issue by kartoFlane** [kartoFlane/ITB-ModLoader#118]
Split off from #111 

Being able to access current set mod options more easily.
A mod's options are defined in `mod_loader.mod_options[mod_id].options` when generated with `modApi:addGenerationOptions`.
However, the information in that table does not reflect the current enable/disable states of options accurately.

Example:
Disabling the first option of a mod will not update `mod_loader.mod_options[mod_id].options[1].enabled`. It will remain `true`.

Maybe updated option information are available elsewhere. If so, it would be helpful to have better documentation on how to deal with options properly. I know it is possible to fetch the options from file, but that does not seem like the most efficient way when there should be cached data somewhere.

**Comment by Lemonymous** [comment]
After having gone through the code to make PR #119, I believe the answer to this issue is the following:
- `mod_loader.mod_options[mod_id].options` contains the option entries in the default configuration as when they were added by the mod. These values don't change.
- `mod_loader.currentModContent[mod_id].options` contain the option entries for the current configuration. These values are updated every time the mod loader "Loads", and is accurate on both mod init and load time. Testing was done on branch used in PR #119.

Since mod option information is indeed available, the only part of this issue that is left to consider, is documentation and/or functions to improve usability. I am not sure what would be the best approach, so any input would be helpful.

**Comment by kartoFlane** [comment]
I think that it's not good that mods have to access specific mod loader fields to access information they need. It should be made available via a function, so that implementation details can be hidden and changed without breaking old mods.

**Comment by kartoFlane** [comment]
Resolved in #121
