### ISSUE TITLE
function Mission.EnumerateSpawns in altered.lua can crash the game.

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#17]
Using the console command `win` while the Vek are surfacing can cause this function to crash the game due to `self.Board` being `nil`.
It is set to nil by `Mission.MissionEnd` in `missions.lua`.

Possible fix: reference `Board` instead of `self.Board` - I don't know the reason `self.Board` is being used though, so maybe this is insufficient.

**Comment by kartoFlane** [comment]
Thanks for letting me know - the `self.Board` is an enhancement that allows referencing Boards of other missions (not just the current one), so in this case switching the reference to regular `Board` would still work. However, it's better to fix the root problem of `self.Board` being reset slightly too early.

Fixed in c949595038ec147e8b8ea388ab2183eaa1288a6a
