### ISSUE TITLE
Game crash (master branch 572 commits)

### ISSUE THREAD

**Issue by Lemonymous** [kartoFlane/ITB-ModLoader#19]
If you win a mission, and then exit to the main menu before the mission ends properly, it crashes with this error:
`[string "line"]:6: attempt to index field 'current_mission' (a nil value)`

**Comment by kartoFlane** [comment]
Fixed in 7f8e214ffcc46c2e1851f35720eee262978b8ff6

There's some room for argument whether this hook should fire once at all once `Game` and `GAME` vars are no longer present, I suppose. Although seeing as `conditionalHook` has a wider range of use cases than just inside of missions, I don't think it should get cleaned up once exiting to main menu (like `runLater` does now), so edge cases have to be handled *somewhere*.
