### ISSUE TITLE
ModLoader superimposed

### ISSUE THREAD

**Issue by c-sanchez** [kartoFlane/ITB-ModLoader#2]
Hi, @kartoFlane a small issue, the menu/text from main menu by ModLoader puts on top over other game menus.
![image1](https://image.ibb.co/fbE0DA/itbmod01xa.png)
![image2](https://image.ibb.co/fkiGmV/itbmod02xa.png)

**Comment by kartoFlane** [comment]
Yes, I'm aware. This is due to the fact that modded UI is, in fact, drawn on top of the game. Unfortunately, fixing this issue requires a lot of effort and fairly fragile code, since we can't detect game's own UI directly. It also has to be coded for every single modded UI element individually.
Not saying it's impossible, just not worth it.

**Comment by c-sanchez** [comment]
I see, well yeah, is just a small issue anyway.
Btw @kartoFlane I'm sorry by make it here, but I don't know where contact with you
I'm looking how translate Into The breach in spanish, I found this is now possible with a mod using ModLoader but I have some doubts.
Please Join to discord to view my topic and read a bit more all, I started the topic on 10-19-2018
https://discordapp.com/channels/417639520507527189/418142041189646336
Although the main doubts are locate at the moment, with _Lemonymous_ who has been helping me so far :)

**Comment by kartoFlane** [comment]
I'm already on the Discord server, and I've seen the conversation. Just haven't commented, I'm not as active there as I used to.
